//index.js
const app = getApp()

Page({
  data: {
    sort: [],
    list: [
      {
        "id": 8200,
        "name": "澳门特别行政区（澳）",
        "pyFirst": "A"
      }, {
        "id": 4105,
        "name": "安阳市",
        "pyFirst": "A"
      }, {
        "id": 5132,
        "name": "阿坝藏族羌族自治州",
        "pyFirst": "A"
      }, {
        "id": 5425,
        "name": "阿里地区",
        "pyFirst": "A"
      }, {
        "id": 2103,
        "name": "鞍山市",
        "pyFirst": "A"
      }, {
        "id": 3408,
        "name": "安庆市",
        "pyFirst": "A"
      }, {
        "id": 5204,
        "name": "安顺市",
        "pyFirst": "A"
      }, {
        "id": 6529,
        "name": "阿克苏地区",
        "pyFirst": "A"
      }, {
        "id": 6543,
        "name": "阿勒泰地区",
        "pyFirst": "A"
      }, {
        "id": 6109,
        "name": "安康市",
        "pyFirst": "A"
      }, {
        "id": 1529,
        "name": "阿拉善盟",
        "pyFirst": "A"
      }, {
        "id": 6204,
        "name": "白银市",
        "pyFirst": "B"
      }, {
        "id": 3403,
        "name": "蚌埠市",
        "pyFirst": "B"
      }, {
        "id": 5205,
        "name": "毕节市",
        "pyFirst": "B"
      }, {
        "id": 3416,
        "name": "亳州市",
        "pyFirst": "B"
      }, {
        "id": 6527,
        "name": "博尔塔拉蒙古自治州",
        "pyFirst": "B"
      }, {
        "id": 6528,
        "name": "巴音郭楞蒙古自治州",
        "pyFirst": "B"
      }, {
        "id": 3716,
        "name": "滨州市",
        "pyFirst": "B"
      }, {
        "id": 4505,
        "name": "北海市",
        "pyFirst": "B"
      }, {
        "id": 2206,
        "name": "白山市",
        "pyFirst": "B"
      }, {
        "id": 4510,
        "name": "百色市",
        "pyFirst": "B"
      }, {
        "id": 2208,
        "name": "白城市",
        "pyFirst": "B"
      }, {
        "id": 5305,
        "name": "保山市",
        "pyFirst": "B"
      }, {
        "id": 6103,
        "name": "宝鸡市",
        "pyFirst": "B"
      }, {
        "id": 1508,
        "name": "巴彦淖尔市",
        "pyFirst": "B"
      }, {
        "id": 5119,
        "name": "巴中市",
        "pyFirst": "B"
      }, {
        "id": 5403,
        "name": "昌都市",
        "pyFirst": "C"
      }, {
        "id": 3417,
        "name": "池州市",
        "pyFirst": "C"
      }, {
        "id": 6523,
        "name": "昌吉回族自治州",
        "pyFirst": "C"
      }, {
        "id": 3204,
        "name": "常州市",
        "pyFirst": "C"
      }, {
        "id": 4514,
        "name": "崇左市",
        "pyFirst": "C"
      }, {
        "id": 5323,
        "name": "楚雄彝族自治州",
        "pyFirst": "C"
      }, {
        "id": 4301,
        "name": "长沙市",
        "pyFirst": "C"
      }, {
        "id": 4307,
        "name": "常德市",
        "pyFirst": "C"
      }, {
        "id": 4310,
        "name": "郴州市",
        "pyFirst": "C"
      }, {
        "id": 5101,
        "name": "成都市",
        "pyFirst": "C"
      }, {
        "id": 2306,
        "name": "大庆市",
        "pyFirst": "D"
      }, {
        "id": 2327,
        "name": "大兴安岭地区",
        "pyFirst": "D"
      }, {
        "id": 2102,
        "name": "大连市",
        "pyFirst": "D"
      }, {
        "id": 6211,
        "name": "定西市",
        "pyFirst": "D"
      }, {
        "id": 3705,
        "name": "东营市",
        "pyFirst": "D"
      }, {
        "id": 1402,
        "name": "大同市",
        "pyFirst": "D"
      }, {
        "id": 3714,
        "name": "德州市",
        "pyFirst": "D"
      }, {
        "id": 5329,
        "name": "大理白族自治州",
        "pyFirst": "D"
      }, {
        "id": 5331,
        "name": "德宏傣族景颇族自治州",
        "pyFirst": "D"
      }, {
        "id": 5334,
        "name": "迪庆藏族自治州",
        "pyFirst": "D"
      }, {
        "id": 5106,
        "name": "德阳市",
        "pyFirst": "D"
      }, {
        "id": 4604,
        "name": "儋州市",
        "pyFirst": "D"
      }, {
        "id": 5117,
        "name": "达州市",
        "pyFirst": "D"
      }, {
        "id": 4207,
        "name": "鄂州市",
        "pyFirst": "E"
      }, {
        "id": 4228,
        "name": "恩施土家族苗族自治州",
        "pyFirst": "E"
      }, {
        "id": 1506,
        "name": "鄂尔多斯市",
        "pyFirst": "E"
      }, {
        "id": 4506,
        "name": "防城港市",
        "pyFirst": "F"
      }, {
        "id": 3501,
        "name": "福州市",
        "pyFirst": "F"
      }, {
        "id": 6404,
        "name": "固原市",
        "pyFirst": "G"
      }, {
        "id": 3607,
        "name": "赣州市",
        "pyFirst": "G"
      }, {
        "id": 4401,
        "name": "广州市",
        "pyFirst": "G"
      }, {
        "id": 5201,
        "name": "贵阳市",
        "pyFirst": "G"
      }, {
        "id": 6230,
        "name": "甘南藏族自治州",
        "pyFirst": "G"
      }, {
        "id": 4503,
        "name": "桂林市",
        "pyFirst": "G"
      }, {
        "id": 4508,
        "name": "贵港市",
        "pyFirst": "G"
      }, {
        "id": 6326,
        "name": "果洛藏族自治州",
        "pyFirst": "G"
      }, {
        "id": 5108,
        "name": "广元市",
        "pyFirst": "G"
      }, {
        "id": 5116,
        "name": "广安市",
        "pyFirst": "G"
      }, {
        "id": 2304,
        "name": "鹤岗市",
        "pyFirst": "H"
      }, {
        "id": 2311,
        "name": "黑河市",
        "pyFirst": "H"
      }, {
        "id": 4106,
        "name": "鹤壁市",
        "pyFirst": "H"
      }, {
        "id": 3401,
        "name": "合肥市",
        "pyFirst": "H"
      }, {
        "id": 3404,
        "name": "淮南市",
        "pyFirst": "H"
      }, {
        "id": 3406,
        "name": "淮北市",
        "pyFirst": "H"
      }, {
        "id": 3410,
        "name": "黄山市",
        "pyFirst": "H"
      }, {
        "id": 6505,
        "name": "哈密市",
        "pyFirst": "H"
      }, {
        "id": 4202,
        "name": "黄石市",
        "pyFirst": "H"
      }, {
        "id": 4211,
        "name": "黄冈市",
        "pyFirst": "H"
      }, {
        "id": 6532,
        "name": "和田地区",
        "pyFirst": "H"
      }, {
        "id": 3717,
        "name": "菏泽市",
        "pyFirst": "H"
      }, {
        "id": 3208,
        "name": "淮安市",
        "pyFirst": "H"
      }, {
        "id": 6302,
        "name": "海东市",
        "pyFirst": "H"
      }, {
        "id": 4511,
        "name": "贺州市",
        "pyFirst": "H"
      }, {
        "id": 4512,
        "name": "河池市",
        "pyFirst": "H"
      }, {
        "id": 6322,
        "name": "海北藏族自治州",
        "pyFirst": "H"
      }, {
        "id": 6323,
        "name": "黄南藏族自治州",
        "pyFirst": "H"
      }, {
        "id": 6325,
        "name": "海南藏族自治州",
        "pyFirst": "H"
      }, {
        "id": 6328,
        "name": "海西蒙古族藏族自治州",
        "pyFirst": "H"
      }, {
        "id": 5325,
        "name": "红河哈尼族彝族自治州",
        "pyFirst": "H"
      }, {
        "id": 4304,
        "name": "衡阳市",
        "pyFirst": "H"
      }, {
        "id": 4312,
        "name": "怀化市",
        "pyFirst": "H"
      }, {
        "id": 6107,
        "name": "汉中市",
        "pyFirst": "H"
      }, {
        "id": 1501,
        "name": "呼和浩特市",
        "pyFirst": "H"
      }, {
        "id": 1507,
        "name": "呼伦贝尔市",
        "pyFirst": "H"
      }, {
        "id": 3301,
        "name": "杭州市",
        "pyFirst": "H"
      }, {
        "id": 3305,
        "name": "湖州市",
        "pyFirst": "H"
      }, {
        "id": 4601,
        "name": "海口市",
        "pyFirst": "H"
      }, {
        "id": 2301,
        "name": "哈尔滨市",
        "pyFirst": "H"
      }, {
        "id": 2308,
        "name": "佳木斯市",
        "pyFirst": "J"
      }, {
        "id": 4108,
        "name": "焦作市",
        "pyFirst": "J"
      }, {
        "id": 3602,
        "name": "景德镇市",
        "pyFirst": "J"
      }, {
        "id": 3604,
        "name": "九江市",
        "pyFirst": "J"
      }, {
        "id": 3608,
        "name": "吉安市",
        "pyFirst": "J"
      }, {
        "id": 6202,
        "name": "嘉峪关市",
        "pyFirst": "J"
      }, {
        "id": 6203,
        "name": "金昌市",
        "pyFirst": "J"
      }, {
        "id": 6209,
        "name": "酒泉市",
        "pyFirst": "J"
      }, {
        "id": 4208,
        "name": "荆门市",
        "pyFirst": "J"
      }, {
        "id": 4210,
        "name": "荆州市",
        "pyFirst": "J"
      }, {
        "id": 3701,
        "name": "济南市",
        "pyFirst": "J"
      }, {
        "id": 3708,
        "name": "济宁市",
        "pyFirst": "J"
      }, {
        "id": 2202,
        "name": "吉林市",
        "pyFirst": "J"
      }, {
        "id": 3304,
        "name": "嘉兴市",
        "pyFirst": "J"
      }, {
        "id": 3307,
        "name": "金华市",
        "pyFirst": "J"
      }, {
        "id": 2303,
        "name": "鸡西市",
        "pyFirst": "J"
      }, {
        "id": 4102,
        "name": "开封市",
        "pyFirst": "K"
      }, {
        "id": 6502,
        "name": "克拉玛依市",
        "pyFirst": "K"
      }, {
        "id": 6530,
        "name": "克孜勒苏柯尔克孜自治州",
        "pyFirst": "K"
      }, {
        "id": 6531,
        "name": "喀什地区",
        "pyFirst": "K"
      }, {
        "id": 5301,
        "name": "昆明市",
        "pyFirst": "K"
      }, {
        "id": 4103,
        "name": "洛阳市",
        "pyFirst": "L"
      }, {
        "id": 111111,
        "name": "陵水黎族自治县",
        "pyFirst": "L"
      }, {
        "id": 5134,
        "name": "凉山彝族自治州",
        "pyFirst": "L"
      }, {
        "id": 4111,
        "name": "漯河市",
        "pyFirst": "L"
      }, {
        "id": 5401,
        "name": "拉萨市",
        "pyFirst": "L"
      }, {
        "id": 5404,
        "name": "林芝市",
        "pyFirst": "L"
      }, {
        "id": 6201,
        "name": "兰州市",
        "pyFirst": "L"
      }, {
        "id": 6212,
        "name": "陇南市",
        "pyFirst": "L"
      }, {
        "id": 5202,
        "name": "六盘水市",
        "pyFirst": "L"
      }, {
        "id": 6229,
        "name": "临夏回族自治州",
        "pyFirst": "L"
      }, {
        "id": 3415,
        "name": "六安市",
        "pyFirst": "L"
      }, {
        "id": 3713,
        "name": "临沂市",
        "pyFirst": "L"
      }, {
        "id": 1410,
        "name": "临汾市",
        "pyFirst": "L"
      }, {
        "id": 3715,
        "name": "聊城市",
        "pyFirst": "L"
      }, {
        "id": 3207,
        "name": "连云港市",
        "pyFirst": "L"
      }, {
        "id": 4502,
        "name": "柳州市",
        "pyFirst": "L"
      }, {
        "id": 2204,
        "name": "辽源市",
        "pyFirst": "L"
      }, {
        "id": 4513,
        "name": "来宾市",
        "pyFirst": "L"
      }, {
        "id": 3508,
        "name": "龙岩市",
        "pyFirst": "L"
      }, {
        "id": 5307,
        "name": "丽江市",
        "pyFirst": "L"
      }, {
        "id": 5309,
        "name": "临沧市",
        "pyFirst": "L"
      }, {
        "id": 3311,
        "name": "丽水市",
        "pyFirst": "L"
      }, {
        "id": 5105,
        "name": "泸州市",
        "pyFirst": "L"
      }, {
        "id": 5111,
        "name": "乐山市",
        "pyFirst": "L"
      }, {
        "id": 2310,
        "name": "牡丹江市",
        "pyFirst": "M"
      }, {
        "id": 3405,
        "name": "马鞍山市",
        "pyFirst": "M"
      }, {
        "id": 5107,
        "name": "绵阳市",
        "pyFirst": "M"
      }, {
        "id": 5114,
        "name": "眉山市",
        "pyFirst": "M"
      }, {
        "id": 3601,
        "name": "南昌市",
        "pyFirst": "N"
      }, {
        "id": 4113,
        "name": "南阳市",
        "pyFirst": "N"
      }, {
        "id": 5424,
        "name": "那曲地区",
        "pyFirst": "N"
      }, {
        "id": 3201,
        "name": "南京市",
        "pyFirst": "N"
      }, {
        "id": 3206,
        "name": "南通市",
        "pyFirst": "N"
      }, {
        "id": 4501,
        "name": "南宁市",
        "pyFirst": "N"
      }, {
        "id": 3507,
        "name": "南平市",
        "pyFirst": "N"
      }, {
        "id": 3509,
        "name": "宁德市",
        "pyFirst": "N"
      }, {
        "id": 5333,
        "name": "怒江傈僳族自治州",
        "pyFirst": "N"
      }, {
        "id": 3302,
        "name": "宁波市",
        "pyFirst": "N"
      }, {
        "id": 5110,
        "name": "内江市",
        "pyFirst": "N"
      }, {
        "id": 5113,
        "name": "南充市",
        "pyFirst": "N"
      }, {
        "id": 4104,
        "name": "平顶山市",
        "pyFirst": "P"
      }, {
        "id": 4109,
        "name": "濮阳市",
        "pyFirst": "P"
      }, {
        "id": 3603,
        "name": "萍乡市",
        "pyFirst": "P"
      }, {
        "id": 6208,
        "name": "平凉市",
        "pyFirst": "P"
      }, {
        "id": 5308,
        "name": "普洱市",
        "pyFirst": "P"
      }, {
        "id": 5104,
        "name": "攀枝花市",
        "pyFirst": "P"
      }, {
        "id": 2309,
        "name": "七台河市",
        "pyFirst": "Q"
      }, {
        "id": 6210,
        "name": "庆阳市",
        "pyFirst": "Q"
      }, {
        "id": 5223,
        "name": "黔西南布依族苗族自治州",
        "pyFirst": "Q"
      }, {
        "id": 5226,
        "name": "黔东南苗族侗族自治州",
        "pyFirst": "Q"
      }, {
        "id": 5227,
        "name": "黔南布依族苗族自治州",
        "pyFirst": "Q"
      }, {
        "id": 3702,
        "name": "青岛市",
        "pyFirst": "Q"
      }, {
        "id": 4507,
        "name": "钦州市",
        "pyFirst": "Q"
      }, {
        "id": 3505,
        "name": "泉州市",
        "pyFirst": "Q"
      }, {
        "id": 5303,
        "name": "曲靖市",
        "pyFirst": "Q"
      }, {
        "id": 3308,
        "name": "衢州市",
        "pyFirst": "Q"
      }, {
        "id": 2302,
        "name": "齐齐哈尔市",
        "pyFirst": "Q"
      }, {
        "id": 3711,
        "name": "日照市",
        "pyFirst": "R"
      }, {
        "id": 2305,
        "name": "双鸭山市",
        "pyFirst": "S"
      }, {
        "id": 6402,
        "name": "石嘴山市",
        "pyFirst": "S"
      }, {
        "id": 2312,
        "name": "绥化市",
        "pyFirst": "S"
      }, {
        "id": 4112,
        "name": "三门峡市",
        "pyFirst": "S"
      }, {
        "id": 1301,
        "name": "石家庄市",
        "pyFirst": "S"
      }, {
        "id": 3611,
        "name": "上饶市",
        "pyFirst": "S"
      }, {
        "id": 4402,
        "name": "韶关市",
        "pyFirst": "S"
      }, {
        "id": 4403,
        "name": "深圳市",
        "pyFirst": "S"
      }, {
        "id": 2101,
        "name": "沈阳市",
        "pyFirst": "S"
      }, {
        "id": 4405,
        "name": "汕头市",
        "pyFirst": "S"
      }, {
        "id": 4203,
        "name": "十堰市",
        "pyFirst": "S"
      }, {
        "id": 4213,
        "name": "随州市",
        "pyFirst": "S"
      }, {
        "id": 3205,
        "name": "苏州市",
        "pyFirst": "S"
      }, {
        "id": 3213,
        "name": "宿迁市",
        "pyFirst": "S"
      }, {
        "id": 2203,
        "name": "四平市",
        "pyFirst": "S"
      }, {
        "id": 2207,
        "name": "松原市",
        "pyFirst": "S"
      }, {
        "id": 3504,
        "name": "三明市",
        "pyFirst": "S"
      }, {
        "id": 4305,
        "name": "邵阳市",
        "pyFirst": "S"
      }, {
        "id": 6110,
        "name": "商洛市",
        "pyFirst": "S"
      }, {
        "id": 3306,
        "name": "绍兴市",
        "pyFirst": "S"
      }, {
        "id": 5109,
        "name": "遂宁市",
        "pyFirst": "S"
      }, {
        "id": 4602,
        "name": "三亚市",
        "pyFirst": "S"
      }, {
        "id": 4603,
        "name": "三沙市",
        "pyFirst": "S"
      }, {
        "id": 1302,
        "name": "唐山市",
        "pyFirst": "T"
      }, {
        "id": 6205,
        "name": "天水市",
        "pyFirst": "T"
      }, {
        "id": 3407,
        "name": "铜陵市",
        "pyFirst": "T"
      }, {
        "id": 5206,
        "name": "铜仁市",
        "pyFirst": "T"
      }, {
        "id": 6504,
        "name": "吐鲁番市",
        "pyFirst": "T"
      }, {
        "id": 1401,
        "name": "太原市",
        "pyFirst": "T"
      }, {
        "id": 3709,
        "name": "泰安市",
        "pyFirst": "T"
      }, {
        "id": 3212,
        "name": "泰州市",
        "pyFirst": "T"
      }, {
        "id": 6542,
        "name": "塔城地区",
        "pyFirst": "T"
      }, {
        "id": 2205,
        "name": "通化市",
        "pyFirst": "T"
      }, {
        "id": 6102,
        "name": "铜川市",
        "pyFirst": "T"
      }, {
        "id": 3310,
        "name": "台州市",
        "pyFirst": "T"
      }, {
        "id": 6403,
        "name": "吴忠市",
        "pyFirst": "W"
      }, {
        "id": 6206,
        "name": "武威市",
        "pyFirst": "W"
      }, {
        "id": 3402,
        "name": "芜湖市",
        "pyFirst": "W"
      }, {
        "id": 6501,
        "name": "乌鲁木齐市",
        "pyFirst": "W"
      }, {
        "id": 4201,
        "name": "武汉市",
        "pyFirst": "W"
      }, {
        "id": 3710,
        "name": "威海市",
        "pyFirst": "W"
      }, {
        "id": 3202,
        "name": "无锡市",
        "pyFirst": "W"
      }, {
        "id": 4504,
        "name": "梧州市",
        "pyFirst": "W"
      }, {
        "id": 5326,
        "name": "文山壮族苗族自治州",
        "pyFirst": "W"
      }, {
        "id": 6105,
        "name": "渭南市",
        "pyFirst": "W"
      }, {
        "id": 1509,
        "name": "乌兰察布市",
        "pyFirst": "W"
      }, {
        "id": 3303,
        "name": "温州市",
        "pyFirst": "W"
      }, {
        "id": 4115,
        "name": "信阳市",
        "pyFirst": "X"
      }, {
        "id": 3605,
        "name": "新余市",
        "pyFirst": "X"
      }, {
        "id": 3418,
        "name": "宣城市",
        "pyFirst": "X"
      }, {
        "id": 4206,
        "name": "襄阳市",
        "pyFirst": "X"
      }, {
        "id": 4209,
        "name": "孝感市",
        "pyFirst": "X"
      }, {
        "id": 4212,
        "name": "咸宁市",
        "pyFirst": "X"
      }, {
        "id": 3203,
        "name": "徐州市",
        "pyFirst": "X"
      }, {
        "id": 6301,
        "name": "西宁市",
        "pyFirst": "X"
      }, {
        "id": 8100,
        "name": "香港特别行政区",
        "pyFirst": "X"
      }, {
        "id": 4303,
        "name": "湘潭市",
        "pyFirst": "X"
      }, {
        "id": 5328,
        "name": "西双版纳傣族自治州",
        "pyFirst": "X"
      }, {
        "id": 6101,
        "name": "西安市",
        "pyFirst": "X"
      }, {
        "id": 6104,
        "name": "咸阳市",
        "pyFirst": "X"
      }, {
        "id": 4331,
        "name": "湘西土家族苗族自治州",
        "pyFirst": "X"
      }, {
        "id": 6401,
        "name": "银川市",
        "pyFirst": "Y"
      }, {
        "id": 2307,
        "name": "伊春市",
        "pyFirst": "Y"
      }, {
        "id": 3606,
        "name": "鹰潭市",
        "pyFirst": "Y"
      }, {
        "id": 3609,
        "name": "宜春市",
        "pyFirst": "Y"
      }, {
        "id": 4205,
        "name": "宜昌市",
        "pyFirst": "Y"
      }, {
        "id": 3706,
        "name": "烟台市",
        "pyFirst": "Y"
      }, {
        "id": 3209,
        "name": "盐城市",
        "pyFirst": "Y"
      }, {
        "id": 3210,
        "name": "扬州市",
        "pyFirst": "Y"
      }, {
        "id": 6540,
        "name": "伊犁哈萨克自治州",
        "pyFirst": "Y"
      }, {
        "id": 4509,
        "name": "玉林市",
        "pyFirst": "Y"
      }, {
        "id": 2224,
        "name": "延边朝鲜族自治州",
        "pyFirst": "Y"
      }, {
        "id": 6327,
        "name": "玉树藏族自治州",
        "pyFirst": "Y"
      }, {
        "id": 5304,
        "name": "玉溪市",
        "pyFirst": "Y"
      }, {
        "id": 4306,
        "name": "岳阳市",
        "pyFirst": "Y"
      }, {
        "id": 4309,
        "name": "益阳市",
        "pyFirst": "Y"
      }, {
        "id": 4311,
        "name": "永州市",
        "pyFirst": "Y"
      }, {
        "id": 6106,
        "name": "延安市",
        "pyFirst": "Y"
      }, {
        "id": 6108,
        "name": "榆林市",
        "pyFirst": "Y"
      }, {
        "id": 5115,
        "name": "宜宾市",
        "pyFirst": "Y"
      }, {
        "id": 5118,
        "name": "雅安市",
        "pyFirst": "Y"
      }, {
        "id": 5120,
        "name": "资阳市",
        "pyFirst": "Z"
      }, {
        "id": 6405,
        "name": "中卫市",
        "pyFirst": "Z"
      }, {
        "id": 4116,
        "name": "周口市",
        "pyFirst": "Z"
      }, {
        "id": 4117,
        "name": "驻马店市",
        "pyFirst": "Z"
      }, {
        "id": 4404,
        "name": "珠海市",
        "pyFirst": "Z"
      }, {
        "id": 6207,
        "name": "张掖市",
        "pyFirst": "Z"
      }, {
        "id": 5203,
        "name": "遵义市",
        "pyFirst": "Z"
      }, {
        "id": 3703,
        "name": "淄博市",
        "pyFirst": "Z"
      }, {
        "id": 3704,
        "name": "枣庄市",
        "pyFirst": "Z"
      }, {
        "id": 1404,
        "name": "长治市",
        "pyFirst": "Z"
      }, {
        "id": 2201,
        "name": "长春市",
        "pyFirst": "Z"
      }, {
        "id": 3506,
        "name": "漳州市",
        "pyFirst": "Z"
      }, {
        "id": 5306,
        "name": "昭通市",
        "pyFirst": "Z"
      }, {
        "id": 4302,
        "name": "株洲市",
        "pyFirst": "Z"
      }, {
        "id": 4308,
        "name": "张家界市",
        "pyFirst": "Z"
      }, {
        "id": 3309,
        "name": "舟山市",
        "pyFirst": "Z"
      }, {
        "id": 5103,
        "name": "自贡市",
        "pyFirst": "Z"
      }]
  },
  scroll (event) {
    let top = event.target.offsetTop
    console.log(top)
    const query = wx.createSelectorQuery()
    debugger
    query.select('.pinyin-' + event.target.dataset.key).boundingClientRect()
    query.selectViewport().scrollOffset()
    query.exec(function(res) {
      if (res[0]) {
        console.log(res[0].top)
        wx.pageScrollTo({
          scrollTop: Math.abs(res[0].top + res[1].scrollTop)
        })
      }
    })
  },
  onLoad: function() {
    const list = this.data.list
    const sort = []
    for (let idx in list) {
      let item = list[idx]
      let cn = item.pyFirst
      let last = list[idx - 1] ? list[idx - 1].pyFirst : ''
      if (cn !== last) {
        sort.push(cn)
      }
    }
    console.log(sort)
    this.setData({
      sort: sort
    })

    // 获取用户信息
    wx.getSetting({
      success: res => {
        if (res.authSetting['scope.userInfo']) {
          // 已经授权，可以直接调用 getUserInfo 获取头像昵称，不会弹框
          wx.getUserInfo({
            success: res => {
              this.setData({
                avatarUrl: res.userInfo.avatarUrl,
                userInfo: res.userInfo
              })
            }
          })
        }
      }
    })
  },

  onGetUserInfo: function(e) {
    if (!this.data.logged && e.detail.userInfo) {
      this.setData({
        logged: true,
        avatarUrl: e.detail.userInfo.avatarUrl,
        userInfo: e.detail.userInfo
      })
    }
  },

  onGetOpenid: function() {
    // 调用云函数
    wx.cloud.callFunction({
      name: 'login',
      data: {},
      success: res => {
        console.log('[云函数] [login] user openid: ', res.result.openid)
        app.globalData.openid = res.result.openid
        wx.navigateTo({
          url: '../userConsole/userConsole',
        })
      },
      fail: err => {
        console.error('[云函数] [login] 调用失败', err)
        wx.navigateTo({
          url: '../deployFunctions/deployFunctions',
        })
      }
    })
  },

  // 上传图片
  doUpload: function () {
    // 选择图片
    wx.chooseImage({
      count: 1,
      sizeType: ['compressed'],
      sourceType: ['album', 'camera'],
      success: function (res) {

        wx.showLoading({
          title: '上传中',
        })

        const filePath = res.tempFilePaths[0]

        // 上传图片
        const cloudPath = 'my-image' + filePath.match(/\.[^.]+?$/)[0]
        wx.cloud.uploadFile({
          cloudPath,
          filePath,
          success: res => {
            console.log('[上传文件] 成功：', res)

            app.globalData.fileID = res.fileID
            app.globalData.cloudPath = cloudPath
            app.globalData.imagePath = filePath

            wx.navigateTo({
              url: '../storageConsole/storageConsole'
            })
          },
          fail: e => {
            console.error('[上传文件] 失败：', e)
            wx.showToast({
              icon: 'none',
              title: '上传失败',
            })
          },
          complete: () => {
            wx.hideLoading()
          }
        })

      },
      fail: e => {
        console.error(e)
      }
    })
  },

})
